#%RAML 0.8
title: aio-adal
version: 1.0
baseUri: https://aio-adal.au.cloudhub.io/api
protocols: [HTTPS]
mediaType: application/json

/authenticate:
  displayName: Authenticate
  description: Uses Azure ADAL to authenticate the user against the provided credentials
  post:
    description: Uses Azure ADAL to authenticate the user against the provided credentials
    body:
      application/x-www-form-urlencoded:
        formParameters:
          username:
            description: Your Azure AD Email address (User Principal Name)
            required: true
            type: string
            example: John_Doe@Microsoft.com.au
          password:
            description: Your Azure AD Password associated with your username
            required: true
            type: string
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "access_token" : "abc123",
                "refresh_token" : "abc123",
                "id_token" : "abc123"
              }
